name: Release
on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["386", "amd64"]
        os: ["linux"]
    steps:
      - name: Setup bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 6.4.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Test"
        run: "bazel test --test_output=errors //..."
      - name: "Build binaries for ${{ matrix.os }}_${{ matrix.arch }}"
        run: "bazel build --platforms=@io_bazel_rules_go//go/toolchain:${{ matrix.os }}_${{ matrix.arch}} --//:name_part_from_command_line=${{ matrix.os }}-${{ matrix.arch }} //:release"
      - name: "Publish ${{ matrix.os }}_${{ matrix.arch }}"
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowUpdates: true
          artifacts: "bazel-bin/bazoekt-${{ matrix.os }}-${{ matrix.arch }}.zip"

