name: Release
on:
  release:
    types: [created]
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
    steps:
      - name: Setup bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: Checkout
        uses: actions/checkout@v4
      - name: Derive version
        id: version
        run: |
          VERSION=$(grep -m1 'version = ' MODULE.bazel | cut -d '"' -f 2)
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
      - name: "Test"
        run: "bazel test --test_output=errors //..."
      - name: "Build binaries for ${{ matrix.os }}_${{ matrix.arch }}"
        run: "bazel build --platforms=@rules_go//go/toolchain:${{ matrix.os }}_${{ matrix.arch}} --//:name_part_from_command_line=${{ matrix.os }}-${{ matrix.arch }} //:release"
      - name: "Publish ${{ matrix.os }}_${{ matrix.arch }}"
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowUpdates: true
          artifacts: "bazel-bin/bazoekt-${{ matrix.os }}-${{ matrix.arch }}.zip"
          tag: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.version }}
          commit: ${{ github.sha }}

